name: Build PHP binaries

on:
  push:
    branches: "**"
    tags-ignore: "php-**"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  everything:
    name: PM${{ matrix.pm-version-major }}
    strategy:
      matrix:
        include:
          - pm-version-major: 4
            latest: false
            recommend: '8.1'
          - pm-version-major: 5
            latest: ${{ github.ref_name == github.event.repository.default_branch }}
            recommend: '8.2'
    uses: ./.github/workflows/build.yml
    with:
      pm-version-major: ${{ matrix.pm-version-major }}
    secrets: inherit
