name: Build PHP binaries (parent workflow)

on:
  push:
    branches: "**"
    tags-ignore: "php-**"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  everything:
    strategy:
      matrix:
        pm-version-major: [4, 5]
    uses: ./.github/workflows/build.yml
    with:
      pm-version-major: ${{ matrix.pm-version-major }}
    secrets: inherit
